Add: Containerfile & cli update

diff --git a/cli/hqt b/cli/hqt
--- a/cli/hqt
+++ b/cli/hqt
@@ -1,11 +1,11 @@
-#!/bin/bash
+#!/bin/sh
 set -u
 set -e
 CLI_VERSION="0.1"
 
 # Heqet Config
 if [ -f Heqetfile ] ; then
-  source Heqetfile
+  . Heqetfile
 else
   echo "Error: Couldn't find Heqetfile in current working directory."
   exit 1
@@ -13,6 +13,7 @@ fi
 HEQET_REPO="${heqet_repo:-https://github.com/nold360/heqet.git}"
 HEQET_REVISION="${heqet_revision:-v3}"
 HEQET_PATH="${heqet_path:-charts/heqet}"
+HEQET_VALUES="${heqet_values:-values.yaml}"
 USERDATA_REPO=$(pwd)
 #USERDATA_REVISION=
 
@@ -29,17 +30,24 @@ done
 function setup {
   if [ ! -d ${HEQET_TMPDIR} ] ; then
 		git clone -b ${HEQET_REVISION} ${HEQET_REPO} ${HEQET_TMPDIR}
-		git -C ${HEQET_TMPDIR} submodule add ${USERDATA_REPO} ${HEQET_TMPDIR}/${HEQET_PATH}/userdata
+		ln -s ${USERDATA_REPO} ${HEQET_TMPDIR}/${HEQET_PATH}/userdata
+    return $?
+  elif [ -L ${HEQET_TMPDIR}/${HEQET_PATH}/userdata ] ; then
+    rm -f ${HEQET_TMPDIR}/${HEQET_PATH}/userdata
+    ln -s ${USERDATA_REPO} ${HEQET_TMPDIR}/${HEQET_PATH}/userdata
+    update
     return $?
   else
-    echo "Directory already exists! '$HEQET_TMPDIR'. Skipping setup"
-    return 0
+    echo "ERROR: Directory '$HEQET_TMPDIR' exists, but '${HEQET_TMPDIR}/${HEQET_PATH}/userdata' is not a softlink."
+    return 1
   fi
 }
 
 function update {
   if [ -d ${HEQET_TMPDIR}/.git ] ; then
-  	git -C ${HEQET_TMPDIR} fetch --all -v --recurse-submodules
+  	git -C ${HEQET_TMPDIR} fetch --all -v
+    git -C ${HEQET_TMPDIR} pull --rebase
+    git -C ${HEQET_TMPDIR} checkout ${HEQET_REVISION}
     return $?
   else
     echo "ERROR: Directory '${HEQET_TMPDIR}' doesn't seem to be a git repo. Did you call 'hqt setup'?"
@@ -49,7 +57,7 @@ function update {
 
 function template {
   if [ -f ${HEQET_TMPDIR}/${HEQET_PATH}/Chart.yaml ] ; then
-    helm template ${HEQET_TMPDIR}/${HEQET_PATH} --set userdata=userdata
+    helm template ${HEQET_TMPDIR}/${HEQET_PATH} -f ${HEQET_VALUES}
     return $?
   else
     echo "ERROR: Couldn't find Chart.yaml in $HEQET_TMPDIR/${HEQET_PATH}. Did you call 'hqt setup'?"
@@ -58,7 +66,7 @@ function template {
 }
 
 function help {
-  echo "Usage: $0 <setup|update|template>"
+  echo "Usage: $0 <setup|update|template|generate>"
   echo "Heqet-CLI v${CLI_VERSION} to setup heqet for helm templating."
   echo "Setup requires ENV-Variables 'USERDATA_REPO' & 'USERDATA_REVISION' of configuration git repo"
 }
@@ -68,6 +76,7 @@ case $param in
   "setup") setup; exit $? ;;
   "update") update; exit $? ;;
   "template") template; exit $? ;;
-  "generate") update &>/dev/null && template; exit $? ;;
+  # This is used by the ArgoCD CM-Plugin:
+  "generate") update &>/dev/null && template 2>/dev/null; exit $? ;;
   *) help; exit 0 ;;
 esac
